### ISSUE TITLE
Help with the logo

### ISSUE THREAD

**Issue by StemateF** [StemateF/blog#2]
If someone could  help me with a logo, i would be very grateful. All i need is a simple logo with my initials or name "SF" (Stemate Florentin).

Unfortunately  i cant relay  pay you ... so all i can do is to  link your  "site" and give you the rights for the logo.

If i wont find anyone that can help me with a logo , i guess i will just  style witch css some text :)

**Comment by Yasujizr** [comment]
Hi!

I sent you an email.

**Comment by Yasujizr** [comment]
Example;

![sf logo](https://user-images.githubusercontent.com/36993664/38469269-9b8acad0-3b5a-11e8-8dcf-7154485d47e7.jpg)

**Comment by StemateF** [comment]
i answered  your email, i dont think i can fit a square logo  on my header, my site is going to be inspired from [https://laravel-news.com/blog](lara-news) since i also suck at creating an original design :(

**Comment by Yasujizr** [comment]
I could not open the site. Logo SF, other places just decorate. But if you do not like it, I can make another design. 

![sf logo](https://user-images.githubusercontent.com/36993664/38469438-684a249c-3b5d-11e8-9e1b-249ce5f6d985.png)

**Comment by StemateF** [comment]
![capture](https://user-images.githubusercontent.com/20905432/38469468-f1a76ef2-3b5d-11e8-9bda-2949dfa863a8.PNG)

![logo](https://user-images.githubusercontent.com/20905432/38469472-fb14ca7a-3b5d-11e8-8ce7-4e6f0e2f0c03.png)
....

i would love a logo that would look like one of those

**Comment by StemateF** [comment]
second logo  got white text on it XD so is invisble

**Comment by Yasujizr** [comment]
I saw it anyway. :) What will the blog be about?

I made a few more examples;

![sf logo2](https://user-images.githubusercontent.com/36993664/38469829-a6aab1b0-3b63-11e8-86ad-f2cf6a25b81a.png)

**Comment by StemateF** [comment]
Nice i like were you are going , the blog is going to be about programming, about problems i faced and how i solved them :)

**Comment by StemateF** [comment]
to be fair i really cant chose between those two , they both look so nice. 

Only one problem you misspelled my name XD

My name is "Stemate Florentin "

**Comment by Yasujizr** [comment]
Oh, I'm so sorry. :) 

I can throw you both if you want. Just tell me what size and format you want.

**Comment by StemateF** [comment]
I would prefer a .png and i only care about height witch should be  44 px .

I think i decided i like the second one more,  so lets just go with that one.

**Comment by StemateF** [comment]
if you could also give me the ps files i would be even more grateful :)

**Comment by Yasujizr** [comment]
You can get it from Link. If you have a problem, you can write to me. Can you add the Logo to the Readme on GitHub? :)

https://drive.google.com/open?id=1tEdU5ixETl5xvQrRgNQ9Rw-Vb9o4Cz8s

**Comment by StemateF** [comment]
yeah, sure i will. Thank you very much for your help i will update the readme tomorrow and add a section of contributors. Do you have any links you want me to put in the contributors section? Beside the github?

**Comment by Yasujizr** [comment]
Github is enough for me. Thank u. :)
