### ISSUE TITLE
Proposal For Copywriting 

### ISSUE THREAD

**Issue by ewuoso** [StemateF/blog#5]
Hello i went through your project and i want to say it is very nice. However i noticed you are missing out some important details like gaq, about us and privacy policy which users will be looking forward too. If you dont mind i can write that for you

contact me
email ewuosoolusesi@gmail.com

steemit.com/@ewuoso

**Comment by StemateF** [comment]
@ewuoso  sure you can write them, no problem :D , if you need info you can ask here

**Comment by ewuoso** [comment]
i am going to ask the questions soon. Are yhu ready?

**Comment by StemateF** [comment]
yeah mate :D bring it on :P

**Comment by ewuoso** [comment]
1 What is stemate Florentine
2 what are the features?
3 what are the benefits
4 what should we expect in future
5 what are the improvements.
6 your contact address

**Comment by ewuoso** [comment]
What do you do on the blog

**Comment by StemateF** [comment]
@ewuoso  i am mostly writing about problems i encounter and how i solved them, like lets say i had a problem with a task, i will post about that and how i solved it.
